spring:
  application:
    name: java-splitwise
  datasource:
    url: jdbc:postgresql://localhost:5433/splitwise
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update   # use 'validate' or 'none' in production
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always